#Section1: Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cpu


In [50]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [51]:
scalar.ndim

0

In [52]:
#Get tensor back as python int

scalar.item()

7

In [53]:
#Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [54]:
vector.ndim

1

In [55]:
vector.shape

torch.Size([2])

In [56]:
#Matrix

MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [57]:
MATRIX.ndim

2

In [58]:
print(MATRIX[0])
MATRIX[1]

tensor([7, 8])


tensor([ 9, 10])

In [59]:
MATRIX.shape

torch.Size([2, 2])

In [60]:
#Tensor

Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [61]:
Tensor.ndim

3

In [62]:
Tensor.shape

torch.Size([1, 3, 3])

###Random tensors

Why Random tensor?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

In [63]:
#Create random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
print(random_tensor)
print(random_tensor.shape)
random_tensor.ndim

tensor([[0.5260, 0.6695, 0.8439, 0.1997],
        [0.4078, 0.7267, 0.5759, 0.3785],
        [0.5040, 0.6410, 0.0381, 0.1465]])
torch.Size([3, 4])


2

In [64]:
#Create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size= (3, 244, 244)) # height, width, color channel
print(random_image_size_tensor)
print(random_image_size_tensor.shape)
random_image_size_tensor.ndim

tensor([[[0.6257, 0.4941, 0.1430,  ..., 0.6183, 0.0064, 0.7254],
         [0.1013, 0.9968, 0.6938,  ..., 0.3758, 0.7510, 0.0327],
         [0.1118, 0.8997, 0.5817,  ..., 0.7230, 0.9341, 0.4689],
         ...,
         [0.0628, 0.0374, 0.6819,  ..., 0.9069, 0.7625, 0.2945],
         [0.9116, 0.0432, 0.9190,  ..., 0.5090, 0.2144, 0.9115],
         [0.1691, 0.1352, 0.5339,  ..., 0.0775, 0.3247, 0.2418]],

        [[0.9485, 0.5465, 0.5636,  ..., 0.5554, 0.5881, 0.7198],
         [0.7799, 0.4928, 0.8613,  ..., 0.8793, 0.8501, 0.5287],
         [0.5004, 0.7335, 0.1719,  ..., 0.5068, 0.6070, 0.3100],
         ...,
         [0.6870, 0.9843, 0.3410,  ..., 0.7233, 0.7091, 0.6174],
         [0.6034, 0.6702, 0.2044,  ..., 0.0918, 0.4413, 0.4890],
         [0.7041, 0.8937, 0.1688,  ..., 0.5716, 0.7920, 0.5228]],

        [[0.2563, 0.3416, 0.1133,  ..., 0.4218, 0.5857, 0.7437],
         [0.6492, 0.4723, 0.7269,  ..., 0.2156, 0.9172, 0.3930],
         [0.9297, 0.5255, 0.3428,  ..., 0.4133, 0.9376, 0.

3

###Zero & Ones

In [65]:
#Create tensor of all zeros

zeros = torch.zeros(size= (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [66]:
zeros.dtype

torch.float32

In [67]:
#Create tensor of all ones

ones = torch.ones(size= (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
ones.dtype

torch.float32

###Creating range of tensors and tensor-like

In [69]:
#Use tensor.arange()

tensor_step = torch.arange(start=1, end=100, step=11)
print(tensor_step)

tensor_arange = torch.arange(start=1, end=11)
tensor_arange

tensor([ 1, 12, 23, 34, 45, 56, 67, 78, 89])


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
#Creating tensor-like

tensor_zero = torch.zeros_like(input=(tensor_arange))
tensor_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

**Note:** Tensor datatype is one of the 3 big errors we'll run into with Pytorch & Deep learning
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on the right device

In [71]:
random_tensor = torch.rand(3, 4)

float_32_tensor = torch.tensor([1.0, 2.0, 15.0],
                               dtype=None, # What datatypes is the tensor (e.g. float32, float64, ...)
                               device=None, # By default device = "cpu"
                               requires_grad=False) # Whether or not to track gradiant with this operations
print(float_32_tensor.dtype)

float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.dtype)

multiple = float_16_tensor * float_32_tensor
print(multiple)

torch.float32
torch.float16
tensor([  1.,   4., 225.])


###Getting Informations from tensors

1.To do get datatype from a tensor, can use `tensor.dtype`
2.To get shape from a tensor, can use `tensor.shape` or `tensor.size`
3.To get device from tensor, can use `tensor.device`

In [72]:
#Crate tensor

some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4476, 0.2003, 0.3197, 0.4583],
        [0.6009, 0.0207, 0.7214, 0.1817],
        [0.9259, 0.0928, 0.7606, 0.4971]])

In [73]:
#Get out detail

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Sahpe of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4476, 0.2003, 0.3197, 0.4583],
        [0.6009, 0.0207, 0.7214, 0.1817],
        [0.9259, 0.0928, 0.7606, 0.4971]])
Datatype of tensor: torch.float32
Sahpe of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
*Addition
*Subtraction
*Multiplication (element-wise)
*Division
*Matrix multiplication

In [2]:
#Addition

tensor = torch.tensor([1, 2, 3])

print(tensor + 10)

torch.add(tensor, 10)

tensor([11, 12, 13])


tensor([11, 12, 13])

In [3]:
#Subtraction

print(tensor - 10)

torch.sub(tensor, 10)

tensor([-9, -8, -7])


tensor([-9, -8, -7])

###Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match (Lenear algebra):

* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimension**

* `(2, 3) @ (3, 2)` --> `(2, 2)`
* `(3, 2) @ (2, 3)` --> `(3, 3)`

In [48]:
#Multiplication (Element-wise)

print(tensor * 10)

torch.mul(tensor, 10)

tensor([10, 20, 30])


tensor([10, 20, 30])

In [4]:
#Multiplication (Matrix)

torch.matmul(tensor, tensor)

tensor(14)

One of the most  common errors  in deep learning: shape errors

In [5]:
# Shape for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

print(tensor_B.shape)
print(tensor_A.shape)
print(tensor_B.T.shape)
# print(torch.matmul(tensor_A, tensor_B))   ##Will not work
print(torch.matmul(tensor_B, tensor_A.T))
torch.mm(tensor_A, tensor_B.T)

torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([2, 3])
tensor([[ 27,  61,  95],
        [ 30,  68, 106],
        [ 33,  75, 117]])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix this kind of shape issues, we can manipulate the shape of one of our tensor using **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [20]:
print(f"Original shapes: tensor_A: {tensor_A.shape}, tensor_B: {tensor_B.shape}")
print(f"new shapes are: tensor_A: {tensor_A.shape} (same as before), tensor_B: {tensor_B.T.shape}")
print(f"Multiplying tensor_A & tensor_B: ")
print("Output:\n")

output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print("\n")
print(f"the shape of output: {output.shape}")

Original shapes: tensor_A: torch.Size([3, 2]), tensor_B: torch.Size([3, 2])
new shapes are: tensor_A: torch.Size([3, 2]) (same as before), tensor_B: torch.Size([2, 3])
Multiplying tensor_A & tensor_B: 
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


the shape of output: torch.Size([3, 3])


Tensor aggregation (Finding min, max, mean, sum, etc)

In [17]:
#Create tensor
x = torch.arange(0, 100, 10)
print(x.dtype)
x

torch.int64


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
#Find the min
print(x.min())
torch.min(x)

tensor(0)


tensor(0)

In [15]:
#Find the max
print(x.max())
torch.max(x)

tensor(90)


tensor(90)

In [18]:
#Find the mean
# torch.mean(x) --> #Error of 'could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long'

# We have to convert the datatype to float32
print(x.type(torch.float32).mean())
torch.mean(x.type(torch.float32))

tensor(45.)


tensor(45.)

In [19]:
#Find the sum
print(x.sum())
torch.sum(x)

tensor(450)


tensor(450)

Finding the positional min & max

In [20]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
# Find the position in tensor that has the minimum value with argmin() --> return the index of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [23]:
# Fint the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

##Reshaping, Stacking, Squeezing & Unsqueezing tensors

* Reshaping --> Reshape an input tensor to a defined shape
* View --> Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking --> Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze --> removes all '1' dimensions from a tensor
* Unsqeeze --> add a '1' dimension to a target tensor
* Permute --> Return a view of the input with dimensions permuted (swapped) in a certain way     

In [29]:
# Create a tensor

x = torch.arange(1., 11.)

x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [31]:
# Reshaping 
# Add an extra dimension

x_reshaped = x.reshape(10, 1) # We dont get error because (10 * 1 = 10) = x.shape
x_reshaped2 = x.reshape(5, 2) # We dont get error because (5 * 2 = 10) = x.shape
x_reshaped, x_reshaped2, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([10, 1]))

In [40]:
# Change the view
z = x.view(1, 10)
print(z)

## Changing z changes x (because a view of a tensor shares the same memory as the original input)

z[: , 0] = 6
x, z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])


(tensor([ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]))

In [41]:
# Stack tensor on top of each other
x_stack = torch.stack([x, x, x, x], dim= 0)
x_stack2 = torch.stack([x, x, x, x], dim= 1)
# x_stack3 = torch.stack([x, x, x, x], dim= 2) # Will give error

x_stack, x_stack2

(tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([[ 6.,  6.,  6.,  6.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]))